### ISSUE TITLE
toolbench.json

### ISSUE THREAD

**Issue by LiamLYYY** [quchangle1/DRAFT#1]
您好，请问DRAFT.py里要读取的toolbench.json文件在哪里

**Comment by quchangle1** [comment]
您好，toolbench.json是Toolllm: Facilitating large language models to master 16000+ real-world apis 这篇文章提出的数据集，您可以在https://github.com/OpenBMB/ToolBench 找到该数据集的介绍等，我们只是将其中关于工具的部分抽取了出来组成了toolbench.json

**Comment by LiamLYYY** [comment]
> 您好，toolbench.json是Toolllm：促进大型语言模型掌握16000+现实世界的api本文文章提出的数据集，您可以在https://github.com/OpenBMB/ToolBench找到该数据集的介绍等，我们只是将其中关于工具的部分抽取出来组成了toolbench.json

您好，感谢回复，请问可以提供一下这个文件吗

**Comment by quchangle1** [comment]
您好，文件在ToolBench的github仓库中有提供下载链接，您可以从那进行下载
