### ISSUE TITLE
rapidapi_key

### ISSUE THREAD

**Issue by LiamLYYY** [quchangle1/DRAFT#2]
您好，请问rapidapi_key的用法能说明一下吗，以及该怎么获取

**Comment by quchangle1** [comment]
由于toolbench中的api是从Rapid API网站中进行搜集的，您可以在官网进行获取自己的rapidapi_key，也可在toolbench仓库中填写对应的表格获取toolbench key进行使用，建议您先阅读toolbench的论文及仓库内容，可以帮助您对这部分的了解

**Comment by STEVENTAN100** [comment]
> 由于toolbench中的api是从Rapid API网站中进行搜集的，您可以在官网进行获取自己的rapidapi_key，也可在toolbench仓库中填写对应的表格获取toolbench key进行使用，建议您先阅读toolbench的论文及仓库内容，可以帮助您对这部分的了解

作者您好！请问rapidapi是需要付费使用的吗？我测试了几个工具都需要subscribe
